// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AnnouncementCard: typeof import('./../components/Announcement/AnnouncementCard.vue')['default']
    AnnouncementForm: typeof import('./../components/Announcement/AnnouncementForm.vue')['default']
    CodeEditor: typeof import('./../components/Shared/CodeEditor.vue')['default']
    CourseSideBar: typeof import('./../components/Course/CourseSideBar.vue')['default']
    CourseTopBar: typeof import('./../components/Course/CourseTopBar.vue')['default']
    DataStatusWrapper: typeof import('./../components/Shared/DataStatusWrapper.vue')['default']
    DueCountdown: typeof import('./../components/Homework/DueCountdown.vue')['default']
    HomeworkCard: typeof import('./../components/Homework/HomeworkCard.vue')['default']
    HomeworkForm: typeof import('./../components/Homework/HomeworkForm.vue')['default']
    HomeworkProblems: typeof import('./../components/Homework/HomeworkProblems.vue')['default']
    IUilAngleDoubleDown: typeof import('~icons/uil/angle-double-down')['default']
    IUilAngleDoubleLeft: typeof import('~icons/uil/angle-double-left')['default']
    IUilAngleDoubleRight: typeof import('~icons/uil/angle-double-right')['default']
    IUilBookAlt: typeof import('~icons/uil/book-alt')['default']
    IUilConstructor: typeof import('~icons/uil/constructor')['default']
    IUilEdit: typeof import('~icons/uil/edit')['default']
    IUilFacebook: typeof import('~icons/uil/facebook')['default']
    IUilGithub: typeof import('~icons/uil/github')['default']
    IUilHome: typeof import('~icons/uil/home')['default']
    IUilLanguage: typeof import('~icons/uil/language')['default']
    IUilMapMarkerInfo: typeof import('~icons/uil/map-marker-info')['default']
    IUilMoon: typeof import('~icons/uil/moon')['default']
    IUilSun: typeof import('~icons/uil/sun')['default']
    IUilTimesCircle: typeof import('~icons/uil/times-circle')['default']
    IUilUser: typeof import('~icons/uil/user')['default']
    JudgeStatus: typeof import('./../components/Submission/JudgeStatus.vue')['default']
    LanguageMultiSelect: typeof import('./../components/Problem/Forms/LanguageMultiSelect.vue')['default']
    LoginSection: typeof import('./../components/Home/LoginSection.vue')['default']
    MarkdownRenderer: typeof import('./../components/Shared/MarkdownRenderer.vue')['default']
    PaginationButtons: typeof import('./../components/Shared/PaginationButtons.vue')['default']
    ProblemCard: typeof import('./../components/Problem/ProblemCard.vue')['default']
    ProblemDescriptionForm: typeof import('./../components/Problem/Forms/ProblemDescriptionForm.vue')['default']
    ProblemForm: typeof import('./../components/Problem/ProblemForm.vue')['default']
    ProblemInfo: typeof import('./../components/Problem/ProblemInfo.vue')['default']
    ProblemInfoCard: typeof import('./../components/Problem/ProblemInfoCard.vue')['default']
    ProblemMultiSelect: typeof import('./../components/Homework/Fields/ProblemMultiSelect.vue')['default']
    ProblemTestdataDescriptionModal: typeof import('./../components/Problem/Forms/ProblemTestdataDescriptionModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SampleCodeBlock: typeof import('./../components/Problem/SampleCodeBlock.vue')['default']
    SideBar: typeof import('./../components/Shared/SideBar.vue')['default']
    SideBarLink: typeof import('./../components/Shared/SideBarLink.vue')['default']
    SkeletonCard: typeof import('./../components/Shared/SkeletonCard.vue')['default']
    SkeletonPost: typeof import('./../components/Shared/SkeletonPost.vue')['default']
    SkeletonTable: typeof import('./../components/Shared/SkeletonTable.vue')['default']
    SystemAnnouncements: typeof import('./../components/Home/SystemAnnouncements.vue')['default']
    TopBar: typeof import('./../components/Shared/TopBar.vue')['default']
    UiSpinner: typeof import('./../components/Shared/UiSpinner.vue')['default']
  }
}
